# Generated by Django 5.0.9 on 2024-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_book_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya qilinsinmi?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Narxi (so'm)"),
        ),
    ]
