# Generated by Django 5.0.9 on 2024-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_book_is_featured_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Baho'),
        ),
    ]
