# Generated by Django 5.0.9 on 2024-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Chegirish qiymati (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Chegirmadami?'),
        ),
    ]
