# Generated by Django 5.0.9 on 2024-10-20 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_alter_book_options_book_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, default="Yo'q", null=True, verbose_name='Tavsif'),
        ),
    ]
